import{a as u,S as m,i as c}from"./assets/vendor-Dpd1z_xS.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();async function f(s,r){const o={method:{per_page:15,page:r,key:"48300565-6dad9db0463f535246b89c980",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return u.get(`https://pixabay.com/api/?${searchParams}`,o)}function y(s){const{largeImageURL:r,webformatURL:o,tags:a,likes:e,views:t,comments:n,downloads:d}=s;return`<a href="${r}" class="gallery-item">
    <div class="photo-card">
      <img src="${o}" alt="${a}" loading="lazy" width="360" />
      <div class="photo-info">
        <p class="photo-info-item">Likes<span>${e}</span></p>
        <p class="photo-info-item">Views<span>${t}</span></p>
        <p class="photo-info-item">Comments<span>${n}</span></p>
        <p class="photo-info-item">Downloads<span>${d}</span></p>
      </div>
    </div>
  </a>`}const l=document.querySelector(".form"),g=document.querySelector(".but-style"),p=document.querySelector(".gallery"),i=document.querySelector(".loader-container"),h=document.querySelector(".but-more"),b=new m(".gallery a",{captionsData:"alt",captionDelay:250,captions:!0});i.style.display="none";const L=async s=>{try{p.innerHTML="",i.style.display="flex",s.preventDefault();const r=l.elements.search.value.trim();if(r===""){i.style.display="none",c.warning({title:"Warning",message:"Enter correct data."});return}l.reset();const o=await f(r);if(o.data.total===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const a=o.data.hits.map(e=>y(e));p.innerHTML=a.join(""),b.refresh()}catch(r){console.log(r)}finally{i.style.display="none"}h.addEventListener("click")};g.addEventListener("submit",L);
//# sourceMappingURL=index.js.map
