import{a as v,S as b,i as p}from"./assets/vendor-Dpd1z_xS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function y(s,t){const a={params:{per_page:15,page:t,key:"48300565-6dad9db0463f535246b89c980",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return v.get("https://pixabay.com/api/",a)}function g(s){const{largeImageURL:t,webformatURL:a,tags:o,likes:e,views:r,comments:c,downloads:L}=s;return`<a href="${t}" class="gallery-item">
    <div class="photo-card">
      <img src="${a}" alt="${o}" loading="lazy" width="360" />
      <div class="photo-info">
        <p class="photo-info-item">Likes<span>${e}</span></p>
        <p class="photo-info-item">Views<span>${r}</span></p>
        <p class="photo-info-item">Comments<span>${c}</span></p>
        <p class="photo-info-item">Downloads<span>${L}</span></p>
      </div>
    </div>
  </a>`}const u=document.querySelector(".form");document.querySelector(".but-style");const m=document.querySelector(".gallery"),l=document.querySelector(".loader-container"),i=document.querySelector(".but-more"),h=new b(".gallery a",{captionsData:"alt",captionDelay:250,captions:!0});l.style.display="none";let n=1,d="";const w=async s=>{try{if(m.innerHTML="",l.style.display="flex",s.preventDefault(),d=u.elements.search.value.trim(),d===""){l.style.display="none",p.warning({title:"Warning",message:"Enter correct data."});return}u.reset(),n=1;const t=await y(d,n);if(t.data.total===0){p.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const a=t.data.hits.map(o=>g(o));m.innerHTML=a.join(""),h.refresh(),t.data.totalHits>15&&(i.classList.remove("is-hidden"),i.removeEventListener("click",f),i.addEventListener("click",f))}catch(t){console.log(t)}finally{l.style.display="none"}};async function f(){try{i.classList.add("is-hidden"),l.style.display="flex",n++;const s=await y(d,n),t=s.data.hits.map(o=>g(o)).join("");m.insertAdjacentHTML("beforeend",t),h.refresh();const a=Math.ceil(s.data.totalHits/15);if(n>=a){p.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}),i.classList.add("is-hidden"),i.removeEventListener("click",f);return}}catch(s){console.log(s)}finally{l.style.display="none",n<Math.ceil(addResponse.data.totalHits/15)&&i.classList.remove("is-hidden")}}u.addEventListener("submit",w);
//# sourceMappingURL=index.js.map
